name: CICD Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: adopt
          java-version: 21
          check-latest: true
      - name: "Account Service - Executing Build Test"
        run: | 
          cd account-service
          ./gradlew clean build
      - name: "Balance Service - Executing Build Test"
        run: |
          cd balance-service
          ./gradlew clean build
