name: CICD Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - app-name: "account-service"
          - app-name: "balance-service"
          - app-name: "cashier-service"
    runs-on: ubuntu-latest
    name: "${{ matrix.app-name }} - build test"
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: adopt
          java-version: 21
          check-latest: true
      - name: Cached Gradle packages
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-v1-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
      - name: "Executing Build Test"
        working-directory: ${{ matrix.app-name }}
        run: |
          ./gradlew clean build
